name: MinecraftButHarder
version: ${project.version}
main: xyz.devshah.minecraftbutharder.MinecraftButHarder
api-version: 1.17
authors: [ DevShah ]
description: Plugin to make Vanilla minecraft difficult to play with some added bonuses
website: https://projects.devshah.xyz/minecraft-but-harder
commands:
  heal:
    description: Heal a player
  feed:
    description: Feed a player
  coordinates:
    description: Get the cords of a player
  spawnboss:
    description: Spawn the Undead King
  givecustom:
    description: Give custom items that the plugin offers

